name: Pack IPKs

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ipkdirectory:
        description: 'name: 要打包的目录, 例如: "XXX 默认打包 ipks'
        required: true
        default: 'ipks'
      ipkinstall:
        description: 'name: 自动运行的文件, 例如: "XXX.sh 默认install.sh'
        required: true
        default: 'install.sh'
        
env:
 MAKESELF_URL: https://github.com/megastep/makeself
 MAKESELF_BRANCH: master
 MATRIX_DIRECTORY: ${GITHUB_WORKSPACE}/makeself
 IPKS_DIRECTORY: ${{ github.event.inputs.ipkdirectory }}
 IPKS_INSTALL: ${{ github.event.inputs.ipkinstall }}
 TZ: Asia/Shanghai

jobs:
  build:
    name: Pack IPKs
    runs-on: ubuntu--latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
 
    - name: Clone source code
      run: |
        git clone $MAKESELF_URL -b $MAKESELF_BRANCH $MATRIX_DIRECTORY

    - name: Packing
      run: |      
       cd &MATRIX_DIRECTORY
       ./makeself.sh --nox11 $GITHUB_WORKSPACE/$IPKS_DIRECTORY &IPKS_DIRECTORY.run "OneClick install" ./$IPKS_INSTALL

    - name: Upload ipks
      uses: actions/upload-artifact@main
      with:
       name: ${{ env.IPKS_DIRECTORY}}
       path: ${{ env.MATRIX_DIRECTORY }}/${{ env.IPKS_DIRECTORY}}.run
